# Sample Application for EKS Cluster Testing
apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    name: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sample-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: sample-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: sample-app
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sample-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>AWS Well-Architected EKS Cluster</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .header { color: #232F3E; }
            .success { color: #4CAF50; }
        </style>
    </head>
    <body>
        <h1 class="header">🎉 EKS Cluster is Working!</h1>
        <p class="success">✅ Your AWS Well-Architected EKS cluster is successfully deployed and running.</p>
        <h2>Cluster Features:</h2>
        <ul>
            <li>Private API endpoint</li>
            <li>Encrypted EBS volumes</li>
            <li>VPC Flow Logs enabled</li>
            <li>CloudWatch logging</li>
            <li>KMS encryption</li>
            <li>IMDSv2 enforced</li>
        </ul>
        <p><strong>Hostname:</strong> <span id="hostname"></span></p>
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
        </script>
    </body>
    </html>